tools/7z: fix build with musl libc
Alone7z fails with error

cc      -O2 -c -Wall -Werror -Wextra  -DNDEBUG -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fPIC  -o _o/CpuArch.o ../../../../C/CpuArch.c
cc      -O2 -c -Wall -Werror -Wextra  -DNDEBUG -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fPIC  -o _o/Delta.o ../../../../C/Delta.c
cc      -O2 -c -Wall -Werror -Wextra  -DNDEBUG -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fPIC  -o _o/LzFind.o ../../../../C/LzFind.c
cc      -O2 -c -Wall -Werror -Wextra  -DNDEBUG -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fPIC  -o _o/Lzma2Dec.o ../../../../C/Lzma2Dec.c
cc      -O2 -c -Wall -Werror -Wextra  -DNDEBUG -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fPIC  -o _o/Lzma2DecMt.o ../../../../C/Lzma2DecMt.c
In file included from ../../../../C/MtDec.h:10,
                 from ../../../../C/Lzma2DecMt.c:30:
../../../../C/Threads.h:80:9: error: unknown type name 'cpu_set_t'
   80 | typedef cpu_set_t CCpuSet;
      |         ^~~~~~~~~
make[3]: *** [../../7zip_gcc.mak:1118: _o/Lzma2DecMt.o] Error 1
make[3]: Leaving directory '/__w/openwrt/openwrt/openwrt/build_dir/host/7z-22.01/CPP/7zip/Bundles/Alone7z'

It seems -D_GNU_SOURCE is needed for cpu_set_t type to correctly work
with musl libc.
Also we need to use a portable variant of pthread_setaffinity that can
work with both glibc and musl libc.

Add the 2 required patch to make 7zip correctly compile with musl libc.

Signed-off-by: Christian Marangi <ansuelsmth@gmail.com>